note/config/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from rest_framework import routers
from rest_app import views


#router = routers.DefaultRouter()
#router.register(r'users', views.UserViewSet)
#router.register(r'notes', views.NoteViewSet)
#router.register(r'users/notes', views.NoteViewSet)


urlpatterns = [
    #url(r'^api/', include(router.urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^note/', include('notes.urls')),
    url(r'^rest_app/', include('rest_app.urls')),    
] 

note/notes/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from notes import views

urlpatterns = [
	#url(r'^$', views.HomeView.as_view(), name='home'),
	url(r'^$', views.NotesListView.as_view(), name='home'),
	url(r'^login/$', views.LoginFormView.as_view(), name='login'),
	url(r'^logout/$', views.LogOutView.as_view(), name='logout'),
	url(r'^sign_up/$', views.RegisterFormView.as_view(), name='sign_up'),
	url(r'^users/$', views.UsersListView.as_view(), name='list_of_users'),
	url(r'^users/(?P<pk>\d+)/$', views.UserProfileView.as_view(), name='user_profile'),
	url(r'^notes/$', views.NotesListView.as_view(), name='list_of_notes'),
	#url(r'^notes/(?P<pk>\d+)/$', views.NoteDetailView.as_view(), name='one_note'),
	url(r'^add_note/$', views.AddNoteFormView.as_view(), name='add_note'),
	url(r'^edit_note/(?P<pk>\d+)/$', views.EditNoteFormView.as_view(), name='edit_note'),
	url(r'^category/(?P<pk>\d+)/$', views.CategoryListOfNotesView.as_view(), name='profile_category'),
	url(r'^add_category/$', views.AddCategoryView.as_view(), name='add_category'),
	url(r'^add_tag/(?P<pk>\d+)/$', views.AddNoteTagView.as_view(), name='add_tag'),
	url(r'^notes_of_tag/(?P<pk>\d+)/$', views.NotesOfTagListView.as_view(), name='notes_of_tag'),
	url(r'^add_subcategory/$', views.AddSubcategoryView.as_view(), name='add_subcategory'),
	url(r'^add_category_to_the_note/(?P<pk>\d+)/$', views.AddNoteCategoryView.as_view(), name='add_note_category'),
	url(r'^delete/(?P<pk>\d+)/$', views.NoteDeleteView.as_view(), name='note_delete'),

] 

note/notes/models.py
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey
import mptt

class Note(models.Model):
	DEFAULT_COLOR = ('black', 'ff0000')
	COLOR_CHOICES = (
		('red', 'ff0000'),
		('green', '00ff00'),
		('blue', '0000ff'),
	)
	author = models.ForeignKey('auth.User', related_name = 'notes')	
	heading = models.CharField(max_length = 100)
	text = models.TextField()
	media_file = models.FileField(upload_to = 'files/', blank = True)
	image = models.ImageField(upload_to = 'img/', blank = True)
	font_color = models.CharField(max_length=10, choices=COLOR_CHOICES, default = DEFAULT_COLOR, blank = True)
	font_size = models.IntegerField(default = 15, blank = True)

	def __unicode__(self):
		return '{0}'.format(self.heading)


class Category(MPTTModel, models.Model):
	category_title = models.CharField(max_length = 100)
	author = models.ForeignKey('auth.User', related_name = 'categories')
	note = models.ManyToManyField(Note, blank = True)
	parent = TreeForeignKey('self', null=True, blank=True, related_name='children', db_index=True)

	class MPTTMeta:
		order_insertion_by = ['category_title']

	def __unicode__(self):
		return '{0}'.format(self.category_title)


class Tag(models.Model):
	tag_name = models.CharField(max_length = 100)
	note = models.ManyToManyField(Note)
	author = models.ForeignKey('auth.User', related_name = 'tags') 
	def __unicode__(self):
		return '{0}'.format(self.tag_name)

note/notes/forms.py
from notes.models import Note, Category, Tag
from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import User
from django.http.request import HttpRequest

class TagForm(forms.Form):
	tag_name = forms.CharField(max_length = 100)


class NoteForm(ModelForm):
	class Meta:
		model = Note		
		fields = ['heading', 'text', 'font_color', 'font_size']


class AddCategoryForm(ModelForm):

	class Meta:
		model = Category
		fields = ['category_title']


class AddSubcategoryForm(forms.Form):
	category = forms.ChoiceField()
	subcategory = forms.CharField(max_length = 100)
	def __init__(self, user, *args, **kwargs):
		super(AddSubcategoryForm, self).__init__(*args, **kwargs)
		self.user = user
		self.fields['category'].choices = [(a,a) for a in Category.objects.filter(author = user)]
		
		
class AddNoteCategoryForm(forms.Form):
	category = forms.ChoiceField()
	def __init__(self, user, *args, **kwargs):
		super(AddNoteCategoryForm, self).__init__(*args, **kwargs)
		self.user = user
		self.fields['category'].choices = [(a,a) for a in Category.objects.filter(author = user)]
	



	

"""
class TagForm(ModelForm):
	
	class Meta:
		model = Tag		
		fields = ['tag_name', 'note']
"""

note/notes/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, DetailView, ListView, View
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from notes.models import Note, Category, Tag 
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.views.generic.edit import FormView, UpdateView, DeleteView
from django.contrib.auth import login, logout
from notes.forms import NoteForm, TagForm, AddCategoryForm, AddSubcategoryForm, AddNoteCategoryForm
from django.core.urlresolvers import reverse_lazy

class HomeView(TemplateView):
	template_name = 'note/home.html'

	@method_decorator(login_required(login_url='/note/login'))
	def dispatch(self, request, *args, **kwargs):
		return super(self.__class__, self).dispatch(request, *args, **kwargs)	


class RegisterFormView(FormView):
	form_class = UserCreationForm
	template_name = 'note/user.html'	
	success_url = '/note'

	def form_valid(self,form):
		form.save()
		return super(RegisterFormView, self).form_valid(form)


class LoginFormView(FormView):
	form_class = AuthenticationForm
	template_name = 'note/log_in.html'	
	success_url = '/note'

	def form_valid(self, form):
		user = form.get_user()
		login(self.request, user)		
		return super(LoginFormView, self).form_valid(form)		

class LogOutView(View):

	def get(self,request,*args,**kwargs):
		logout(self.request)
		return redirect('/note')


class UsersListView(ListView):
	template_name = 'note/get_readers.html'
	model = User

	@method_decorator(login_required(login_url='/note/login'))
	def dispatch(self, request, *args, **kwargs):
		return super(self.__class__, self).dispatch(request, *args, **kwargs)

	"""
	def get(self,request,*args,**kwargs):
		
		request.session.set_expiry(60)
		request.session['pause'] = True		
		
		return render(request, self.template_name, {'user_list': User.objects.all()})
	"""	

class UserProfileView(DetailView):
	model = User
	template_name = 'user_profile/profile.html'

	def get_context_data(self, **kwargs):
		user=self.object		
		context = super(UserProfileView,self).get_context_data(**kwargs)

		context['category'] = Category.objects.filter(author = user)	
		return context


	@method_decorator(login_required(login_url='/note/login'))
	def dispatch(self, request, *args, **kwargs):
		return super(self.__class__, self).dispatch(request, *args, **kwargs)

class NotesListView(ListView):
	template_name = 'note/home.html'
	model = Note

	@method_decorator(login_required(login_url='/note/login'))
	def dispatch(self, request, *args, **kwargs):
		return super(self.__class__, self).dispatch(request, *args, **kwargs)


class AddNoteFormView(FormView):
	form_class = NoteForm
	template_name = 'note/add_note.html'
	success_url = '/note/users/'
	
	def form_valid(self, form):		
		self.object = form.save(commit=False)
		self.object.author = self.request.user
		self.object.save()
		return super(AddNoteFormView, self).form_valid(form)


class EditNoteFormView(UpdateView):
	fields = ('heading','text','image', 'media_file', 'font_color', 'font_size')	
	model = Note
	template_name = 'note/edit_note.html'
	success_url = '/note/users/'



class CategoryListOfNotesView(DetailView):
	template_name = 'user_profile/profile_category.html'
	model = Category

	def get_context_data(self, **kwargs):
		user = self.request.user
		category=self.object
		context = super(CategoryListOfNotesView,self).get_context_data(**kwargs)		
		context['notes'] = self.object.note.all()
		context['category_title'] = category.category_title
		context['category'] = Category.objects.filter(author=user)	
		return context


class AddNoteTagView(FormView):
	form_class = TagForm
	template_name = 'note/add_tag.html'
	success_url = reverse_lazy('list_of_users')
	
	def form_valid(self, form):		
		tag_name = form.cleaned_data['tag_name']
		author = self.request.user
		#print tag_exist, heading
		note_id = str(self.request.path).split('/')
		note = Note.objects.get(id = note_id[3])
		if Tag.objects.filter(tag_name = tag_name).exists():
			Tag.objects.get(tag_name = tag_name).note.add(note)
		else:	
			tag = Tag.objects.create(tag_name = tag_name, author = author)
			tag.note.add(note)
		return super(AddNoteTagView, self).form_valid(form)
	"""
	def form_valid(self, form):		
		self.object = form.save(commit=False)
		self.object.note_id = self.request.session[str(self.request.path)]
		print self.object
		self.object.save()		
		return super(AddNoteTagView, self).form_valid(form)
	"""	

class NotesOfTagListView(DetailView):
	template_name = 'user_profile/profile_tag.html'
	model = Tag

	def get_context_data(self, **kwargs):
		user = self.request.user
		tag = self.object
		context = super(NotesOfTagListView,self).get_context_data(**kwargs)		
		context['category'] = Category.objects.filter(author=user)
		context['notes'] = {tag: tag.note.all()}		
		return context


class AddCategoryView(FormView):
	form_class = AddCategoryForm
	template_name = 'note/add_category.html'
	success_url = '/note/users/'

	def form_valid(self, form, *args, **kwargs):
		
		self.object = form.save(commit = False)
		self.object.author = self.request.user
		self.object.save()
		return super(AddCategoryView, self).form_valid(form)


class AddSubcategoryView(FormView):
	form_class = AddSubcategoryForm
	template_name = 'note/add_subcategory.html'
	success_url = '/note/users/1'

	def get_form_kwargs(self):
		kwargs = super(AddSubcategoryView, self).get_form_kwargs()
		kwargs['user'] = self.request.user
		return kwargs

	def form_valid(self, form, *args, **kwargs):
		category = form.cleaned_data['category']		
		parent_category = Category.objects.get(category_title = category)		
		subcategory = form.cleaned_data['subcategory']		
		author = self.request.user		
		Category.objects.create(
			category_title = subcategory,
			parent = Category.objects.get(category_title = category),
			author = author)
		return super(AddSubcategoryView, self).form_valid(form)


class AddNoteCategoryView(FormView):
	form_class = AddNoteCategoryForm
	template_name = 'note/add_note_category.html'
	success_url = '/note/users/'	

	def get_form_kwargs(self):
		kwargs = super(AddNoteCategoryView, self).get_form_kwargs()
		kwargs['user'] = self.request.user
		return kwargs

	def form_valid(self, form, *args, **kwargs):
		category = form.cleaned_data['category']
		print category
		a = str(self.request.path).split('/')
		note = Note.objects.get(id = a[3])
		print a, note
		aa = Category.objects.get(category_title = category)
		print aa
		Category.objects.get(category_title = category).note.add(note)	
		return super(AddNoteCategoryView, self).form_valid(form)


class NoteDeleteView(DeleteView):
	model = Note
	success_url = '/note/'
	template_name = 'note/note_confirm_delete.html'

	@method_decorator(login_required(login_url='/user/log_in'))
	def dispatch(self, request, *args, **kwargs):
		return super(self.__class__, self).dispatch(request, *args, **kwargs)

note/templates/note/add_category.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
	<form action='' method="POST" enctype="multipart/form-data" class="add_new_author">
		<fieldset>
    	<legend>Adding</legend>	
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" class="btn btn-success"/>
		</fieldset>
	</form>
</div>		
{% endblock %}

note/templates/note/add_note.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
	<form action='' method="POST" enctype="multipart/form-data" class="add_new_author">
		<fieldset>
    	<legend>Adding</legend>	
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" class="btn btn-success"/>
		</fieldset>
	</form>
</div>		
{% endblock %}

note/templates/note/add_note_category.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
		<p>	
		{{ form.errors }}
		</p>
		<form action ='' method = "post">
			<div class="row">
				<div class="col-xs-6">
					{% csrf_token %}
					
					<label for = "categories">Choose:</label>
					<select id = "categories" name = "category">
							{% for a, a in form.fields.category.choices %}
								
							<option value="{{ a }}">{{ a }}</option>
							{% endfor %}		
					</select>
					
					<input type="submit" class="btn btn-success"/>			
				</div>
			</div>			
		</form>	
</div>
{% endblock %}

note/templates/note/add_tag.html
{% extends 'base.html' %}
{% block content %}

	<div class="container-fluid">
		<p>	
		{{ form.errors }}
		</p>
		<form action ='' method = "post">
			<div class="row">
				<div class="col-xs-6">
					{% csrf_token %}
					<h1 class="text-center radius">Select a note</h1>
					
					<h1>Input tag name</h1>
					<input name = "tag_name">
						{{ form.form.tag_name }} </input>					
												
					<input type = "submit" value = "Send" class=" btn-info btn-sm my_button" />
					</div>	
			</form>	
		</div>
			
{% endblock %}

note/templates/note/edit_note.html
{% extends 'base1.html' %}
{% block content %}
<div class="container-fluid">
	<form action='' method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form.as_p }}
	<input type="submit"/>
	</form>
</div>
	
{% endblock %}

note/templates/note/get_list.html
{% extends 'base.html' %}
{% block content %}
{% load cache %}
<!--
{% cache 50 author %}
-->
<div class="container-fluid">
	<h2 class="author_color">Choose the author below:</h2>
	{% for author in author_list %}
	<ul class="list-group inl_block">		
		<li class="list-group-item">

			<a href="{% url 'one_author' author.pk %}">{{ author }}
				<li class="list-group-item">
					<img src="{{ author.profile_image.url }}" class="img_size_130"/>
				</li>
			</a>

		</li>
		<li class="list-group-item">
			<a href="{% url 'delete_author' author.pk %}">Delete</a>
		</li>
	</ul>
	{% endfor %}
	
</div>
<!--
{% endcache %}
-->
{% endblock %}

note/templates/note/get_readers.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
	<h2 class="author_color">Choose the reader below:</h2>

	<ul class="list-group"  id='users'>		
		
	</ul>

</div>

<script>
	$.get("http://127.0.0.1:8000/rest_app/users/",function(res){
		res.forEach(function(item){
			$("#users").append('<a href="'+item.id+'"><li class="list-group-item ">'+item.username+'</li></a>');
				
		});
	})
</script>
{% endblock %}

note/templates/note/home.html
{% extends 'base.html' %}

{% block content %}

	<div class="container-fluid">
       <div class="row">
			<div class="col-xs-8" >
				<h1 class="text-center roww radius">Notes:</h1>
								
				<ul class="list-group" id="blah">
				</ul>
								
			</div>

			<div class="col-xs-4">
            	<h1 class="text-center roww radius">_</h1>
                    <ul class="list-group">
                        <li class="list-group-item radiusli"><a href="{% url 'user_profile' user.pk %}">My page</a></li>     
                        <li class="list-group-item radiusli"><a href="{% url 'list_of_users' %}">All users</a></li>
                    </ul>
  
            </div>
					
		</div>	
	
	</div>

<script>
	

	$.get("http://127.0.0.1:8000/rest_app/notes/",function(res){
		res.forEach(function(item){
			$("#blah").append('<li class="list-group-item radiusli">'+item.author+' '+item.heading+'</li>');
				
		});
	})
</script>
{% endblock %}

note/templates/note/home_not_rest.html
{% extends 'base.html' %}

{% block content %}

	<div class="container-fluid">
       <div class="row">
			<div class="col-xs-8">
				<h1 class="text-center roww radius">Notes:</h1>

				<ul class="list-group">

				{% for note in note_list %}	
					<li class="list-group-item radiusli">
						{{ note.author }}
						<ul class="list-group">
							<li class="list-group-item radiusli">
							{{ note.heading }}
							</li>
						</ul>
					</li>	
				
				{% empty %}
					<li class="list-group-item">No notes</li>	
				{% endfor %}
				</ul>

			</div>

			<div class="col-xs-4">
            		<h1 class="text-center roww radius">_</h1>
                    <ul class="list-group">
                        <li class="list-group-item radiusli"><a href="{% url 'user_profile' user.pk %}">My page</a></li>      
                        <li class="list-group-item radiusli"><a href="{% url 'user_profile' user.pk %}">My friends</a></li>
                        <li class="list-group-item radiusli"><a href="{% url 'user_profile' user.pk %}">My notes</a></li> 

                    </ul>
                
                
            </div>
					
		</div>	
		
		
	</div>

{% endblock %}

note/templates/note/log_in.html
{% extends 'base.html' %}
{% block content %}
{% block log_in %}
	{% if user.is_authenticated %}
	<p>Welcome, {{ user.username }}</p>

	{% else %}
	<p>Welcom, new user. Please log in.</p>
	<form action='' method='Post'>

	{{ form.as_p }}
		{% csrf_token %}
	<input type="submit" />
	</form>

	{% endif %}

{% endblock %}
{% endblock %}

note/templates/note/note_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
    <h1 class='color_h1'>Do you want to delete {{ note }}?</h1>
        <form action="" method="post">
            {% csrf_token %}
            <input class="btn btn-success btn-lg" type="submit" value="Yes"/>
            <a href='{% url "list_of_users" %}' class="btn btn-success btn-lg">No</a>
        </form>
    

{% endblock %}

note/templates/note/thanks.html
{% extends 'base.html' %}
{% block content %}

<div class="container-fluid">
	<h2 class="bg">Success.You will see yourself on the main page.
	</h2>	
	<a class="btn btn-success btn-lg" href="../" role="button">Go Back</a>	
	
</div>		

{% endblock %}

note/templates/note/user.html
{% extends 'base.html' %}
{% block content %}
<form action='' method='Post'>
{{ form.as_p }}
	{% csrf_token %}
<input type="submit" />
</form>
{% endblock %}

note/templates/note/user_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
    <h1 class='color_h1'>Do you want to delete {{ user }}?</h1>
        <form action="" method="post">
            {% csrf_token %}
            <input class="btn btn-success btn-lg" type="submit" value="Yes"/>
            <a href='{% url "list_of_readers" %}' class="btn btn-success btn-lg">No</a>
        </form>
    

{% endblock %}